### ISSUE TITLE
Remove unnecessary elements

### ISSUE THREAD

**Issue by ashishpahwa7** [Indian-Youth-Climate-Network/Indian-Youth-Climate-Network.github.io#51]
Remove unnecessary elements that are inherited from template but are not relevant for this website.

**Comment by KamalNanda** [comment]
Removed team option from nav bar 
Removed theGov logo

**Comment by ashish-iycn** [comment]
Please take care of this on all pages.

**Comment by KamalNanda** [comment]
removed team option on navbar from all the pages

**Comment by ashish-iycn** [comment]
Seems like you have not raised the PR for same.

**Comment by KamalNanda** [comment]
removed contact us btn from navbar, 
made view all btn from recent event section working, it redirects to events page now
